### ISSUE TITLE
App crashes after dismissing the FormSheet

### ISSUE THREAD

**Issue by pahnev** [curciosobrinho/NavAutoDismiss#1]
That's it. Without any good error I get a crash when I try to do something after dismiss happens.
iOS 8.1.2

**Comment by Donnit** [comment]
That's because in viewWillDisappear    

```
[view removeGestureRecognizer:tapBehindGesture]; 
```

should be

```
[view.window removeGestureRecognizer:tapBehindGesture];
```

**Comment by curciosobrinho** [comment]
Closing as the code was updated
